# Generated by Django 4.0.10 on 2023-08-31 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echolink', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('visualizacao', models.IntegerField()),
                ('pixiv', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('profile_picture2', models.ImageField(blank=True, null=True, upload_to='profile_pictures2/')),
            ],
            options={
                'verbose_name': 'Echo',
                'verbose_name_plural': 'Echoes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pixiv_user', models.CharField(blank=True, max_length=255)),
                ('biografia', models.TextField(blank=True, default=' ')),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
